# Generated by Django 5.0 on 2023-12-07 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avtomobile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
